package tablas;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated Nov 23, 2019 1:39:02 PM by Hibernate Tools 5.4.7.Final

/**
 * Apelacion generated by hbm2java
 */
@Entity
@Table(name="Apelacion")
public class Apelacion implements java.io.Serializable {
	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
	private int idApelacion;
	private String motivo;
	private String estado;

	public Apelacion() {
	}

	public Apelacion(int idApelacion) {
		this.idApelacion = idApelacion;
	}

	public Apelacion(int idApelacion, String motivo, String estado) {
		this.idApelacion = idApelacion;
		this.motivo = motivo;
		this.estado = estado;
	}

	public int getIdApelacion() {
		return this.idApelacion;
	}

	public void setIdApelacion(int idApelacion) {
		this.idApelacion = idApelacion;
	}

	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
