package tablas;
// Generated Nov 23, 2019 1:39:02 PM by Hibernate Tools 5.4.7.Final

/**
 * Multa generated by hbm2java
 */
public class Multa implements java.io.Serializable {

	private int idmulta;
	private String calle;
	private String tipo;
	private Integer velocidad;
	private String avenida;
	private String pasaje;

	public Multa() {
	}

	public Multa(int idmulta) {
		this.idmulta = idmulta;
	}

	public Multa(int idmulta, String calle, String tipo, Integer velocidad, String avenida, String pasaje) {
		this.idmulta = idmulta;
		this.calle = calle;
		this.tipo = tipo;
		this.velocidad = velocidad;
		this.avenida = avenida;
		this.pasaje = pasaje;
	}

	public int getIdmulta() {
		return this.idmulta;
	}

	public void setIdmulta(int idmulta) {
		this.idmulta = idmulta;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Integer getVelocidad() {
		return this.velocidad;
	}

	public void setVelocidad(Integer velocidad) {
		this.velocidad = velocidad;
	}

	public String getAvenida() {
		return this.avenida;
	}

	public void setAvenida(String avenida) {
		this.avenida = avenida;
	}

	public String getPasaje() {
		return this.pasaje;
	}

	public void setPasaje(String pasaje) {
		this.pasaje = pasaje;
	}

}
